name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readme-typing-svg/recent-repos@v1
        with:
          username: dilshod1405
          max_repos: 5
